const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || 'http://localhost:5000';

const ROLES = {
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
  ALUMNI: 'ALUMNI',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

const CAMPUS_TYPES = {
  MAIN: 'MAIN',
  TOWN: 'TOWN',
  SATELLITE: 'SATELLITE',
};

const REACTION_TYPES = {
  LIKE: 'LIKE',
  LOVE: 'LOVE',
  HAHA: 'HAHA',
  WOW: 'WOW',
  SAD: 'SAD',
  ANGRY: 'ANGRY',
};

const POST_PRIVACY = {
  PUBLIC: 'PUBLIC',
  CAMPUS_ONLY: 'CAMPUS_ONLY',
  DEPARTMENT_ONLY: 'DEPARTMENT_ONLY',
  FRIENDS_ONLY: 'FRIENDS_ONLY',
};

const STORY_PRIVACY = {
  PUBLIC: 'PUBLIC',
  CAMPUS_ONLY: 'CAMPUS_ONLY',
  FRIENDS_ONLY: 'FRIENDS_ONLY',
};

const MESSAGE_TYPES = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  VOICE: 'VOICE',
  FILE: 'FILE',
  SYSTEM: 'SYSTEM',
};

const LISTING_STATUS = {
  ACTIVE: 'ACTIVE',
  SOLD: 'SOLD',
  REMOVED: 'REMOVED',
};

const EVENT_STATUS = {
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
};

export {
  API_URL,
  SOCKET_URL,
  ROLES,
  CAMPUS_TYPES,
  REACTION_TYPES,
  POST_PRIVACY,
  STORY_PRIVACY,
  MESSAGE_TYPES,
  LISTING_STATUS,
  EVENT_STATUS,
  PAGINATION,
};